default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: username
      password: password
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: rspec_blog_development

test:
  <<: *default
  database:rspec_blogr_test

production:
  <<: *default
  database: rspec_blog_production